/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "fmvebmnfkviuwmgllxke"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtdmVibW5ma3ZpdXdtZ2xseGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNjgxMjUsImV4cCI6MjA4NTY0NDEyNX0.-dZ8TXvqPP6w85PVor7umrLOkp-Mjs-dEGowpFLE6lM"